本着实用的原则（其实主要原因是博主的理论知识也只是自己心里明白，做不到给大家讲明白的程度），
这部分就不讲太多关于数据库隔离级别以及不同隔离级别并发时出现的结果等等。

我们使用最简单的Product类进行测试，先写入一条数据：


```C#
var product = new Product() { Name = "投影仪", Description = "高分辨率" };

context.Set<Product>().Add(product);

context.SaveChanges(); 
```

然后我们编写一个并发测试类来模拟2个用户同时编辑同一个Product的情况：


```C#
public class ConcurrencyTest : IDisposable

{

    private readonly DbContext _user1Context;

    private readonly DbContext _user2Context;

 

    public ConcurrencyTest()

    {

        _user1Context = new CodeFirstForBlogContext();

        _user2Context = new CodeFirstForBlogContext();

    }

 

    public void EditProductConcurrency()

    {

        User1Edit();

        User2Edit();

        User2Save();

        User1Save();

    }

 

    private void User1Edit()

    {

        var product = _user1Context.Set<Product>().First();

        product.Name = product.Name +" edited by user1 at " + DateTime.Now.ToString("MM-dd HH:mm:ss");

    }

 

    private void User1Save()

    {

        _user1Context.SaveChanges();

    }

 

    private void User2Edit()

    {

        var product = _user2Context.Set<Product>().First();

        product.Name = product.Name + " edited by user2 at " + DateTime.Now.ToString("MM-dd HH:mm:ss");

    }

 

    private void User2Save()

    {

        _user2Context.SaveChanges();

    }

 

 

    public void Dispose()

    {

        Dispose(true);

        GC.SuppressFinalize(this);

    }

 

    protected virtual void Dispose(bool disposing)

    {

        if (disposing == true)

        {

            _user1Context.Dispose();

            _user2Context.Dispose();

        }

    }

 

    ~ConcurrencyTest()

    {

        Dispose(false);

    }

} 

```
我们之前看到的那些Fluent API配置都没有启用并发支持，我们在没有并发支持的情况下看看这段代码的执行情况：

```C#

using (ConcurrencyTest test = new ConcurrencyTest())

{

    test.EditProductConcurrency();

} 
```

运行，我们可以看到在User2Save执行后被写入的数据，完全被User1Save所写入的数据覆盖了。也就是说User2的修改丢失了。

*怎样避免呢，这就需要启用并发支持。EF只支持乐观并发，以上面情况为例也就是说当出现上面情况时EF会抛出异常(DbUpdateConcurrencyException)，
使User1无法提交，从而保护User2的修改不被覆盖。*

*怎么启用并发乐观支持呢？*

我们给Product添加一个属性标识数据版本，属性名随意起，类型必须是byte[]。


```C#

public byte[] RowStamp { get; set; } 
```

在Fluent API中需要这样配置以指定RowStamp作为并发标识：


```C#
Property(p => p.RowStamp).IsRowVersion(); 
```

重新执行迁移，然后在运行之前的并发测试方法，此时User1Save方法调用时就会报异常，如图：



图3. 乐观并发开启时同时编辑导致的异常
![](http://images0.cnblogs.com/blog2015/42044/201508/072001031127286.png)

怎样处理这中情况呢？有很多种策略。我们先修改一下User1Save，在其中捕获一下DbUpdateConcurrencyException，我们的处理实在这个异常的catch中完成的。


```C#
private void User1Save()

{

    try

    {

        _user1Context.SaveChanges();

    }

    catch (DbUpdateConcurrencyException concurrencyEx)

    {

        //处理异常

    }

} 
```

* 策略1：使用数据库数据

    异常处理部分代码如下：


    ```C#


    catch (DbUpdateConcurrencyException concurrencyEx)

    {

        concurrencyEx.Entries.Single().Reload();

        _user1Context.SaveChanges();

    } 
    ```

    Reload表示由数据库中重新加载数据并覆盖当前保存失败的对象。这样User2的修改会被保存下来，User1的修改丢失。如同不在catch中做任何处理的效果。 

 

策略2：使用客户端数据

    异常处理部分代码如下：

    ```C#

    catch (DbUpdateConcurrencyException concurrencyEx)

    {

        var entry = concurrencyEx.Entries.Single();

        entry.OriginalValues.SetValues(entry.GetDatabaseValues());

        _user1Context.SaveChanges();

    } 

    ```
    使用数据库获取的值来填充保存失败的对象的OriginalValues属性(原始值)，这样这个保存失败对象(User1的修改)再次提交时，
    数据库就不会因为原始值(OriginalValues)与数据库里现有值不同而产生异常了。最终结果就是User1的修改被保存，User2的修改被覆盖。
    这种结果和不启用乐观并发是一样的。

 

策略3：由用户决定合并结果

    异常处理部分代码如下：

    ```C#

    catch (DbUpdateConcurrencyException concurrencyEx)

    {

 

        var entry = concurrencyEx.Entries.Single();

        var databaseValues = entry.GetDatabaseValues();

        var currentEntity = (Product)entry.CurrentValues.ToObject();

        var databaseEntity = (Product)entry.GetDatabaseValues().ToObject();

 

        // 我们将数据库的现有值作为默认的合并结果。合并过程中可以在这基础上修改。

        var resolvedEntity = (Product)databaseValues.Clone().ToObject();

 

        // 在这个函数中，用户实现合并方法决定最终写入数据库的值

        UserResolveConcurrency(currentEntity, databaseEntity, resolvedEntity);

 

        // 同样要把数据库的值写入OriginalValues，以保证不在此触发并发异常

        // 把合并值作为CurrentValues，其将被提交到数据库

        entry.OriginalValues.SetValues(databaseValues);

        entry.CurrentValues.SetValues(resolvedEntity);

 

        _user1Context.SaveChanges();

    } 
    ```

    道理很简单，我们就是分别取出现有值和数据库值，留给用户去决定合并结果并提交回数据库。通过代码中注释可以很容易理解。

    其中调用的合并函数如下：


    ```C#

    private void UserResolveConcurrency(Product currentEntity, Product databaseEntity, Product resolvedEntity)

    {

        //由用户决定 怎样合并currentEntity和databaseEntity得到resolvedEntity

        Debug.WriteLine(string.Format("current(user1):Name-{0}",currentEntity.Name));

        Debug.WriteLine(string.Format("database(user2):Name-{0}", databaseEntity.Name));

        resolvedEntity.Name = resolvedEntity.Name + " Merged by user1";

    } 
    ```

    当然这个函数是随便实现的，大家应该根据实际业务场景仔细设计这个函数的实现。

    根据这个函数的实现，程序执行后，最终Product的Name被更新为：投影仪 edited by user2 at 08-07 21:12:18 Merged by user1

 


>除了对整行启用乐观并发支持外，还可以针对单个列启用乐观并发支持。如我们可以使用下面的代码把Product的Name属性配置为受乐观并发管理。
>
>
>```C#
>Property(p => p.Name).IsConcurrencyToken(); 
>```
>    
>这样只有当Name出现并发修改时，才会抛出异常，异常的处理方式与之前介绍的相同。
 
